name: Build and Deploy to Netlify

on:
  push:
    branches:
      - fix/build # change this to the branch you want to build and deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies and build
      run: |
        npm ci
        npm run crowndin:sync
        npm run build
