name: Build and Deploy to Netlify

on:
  push:
    branches:
      - build-fix # change this to the branch you want to build and deploy from

jobs: # Test commit
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install

    - name: crowdin action
      uses: crowdin/github-action@v1
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Build
      run: |
        npm run build

