name: Preview deployment on netlify

on:
  pull_request:
    branches:
      - main

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install

    - name: Build
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm run build

    - name: Deploy preview to Netlify
      id: deploy
      run: |
        OUTPUT=$(netlify deploy --dir=build --json)
        TRIMMED_OUTPUT=$(echo "$OUTPUT" | tr -d '%')
        echo "Deploy Output: $TRIMMED_OUTPUT"
        echo "::set-output name=stdout::$TRIMMED_OUTPUT"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Comment PR with preview URL
      uses: actions/github-script@v5
      with:
        script: |
          const deployOutput = '${{ steps.deploy.outputs.stdout }}';
          console.log('Deploy Output:', deployOutput);

          if (deployOutput) {
            try {
              const deployData = JSON.parse(deployOutput);
              const previewUrl = deployData.deploy_url;
              const commentBody = `:rocket: Preview deployment: [${previewUrl}](${previewUrl})`;
              console.log("commentBody = ", commentBody")
            } catch (error) {
              console.error('Error parsing JSON:', error);
            }
          } else {
            console.error('No deploy output found');
